Ayasinovsky/feature/30
it-beard/bloggers-cms pull request #117
Opened 2021-04-17 13:11 UTC by Alex2021cyberhuman

#30 #94

2021-04-19 13:19 UTC, itbeard commented on Pds/Pds.Api.Contracts/Topic/CheckBoxPersonDto.cs
> +﻿using Pds.Api.Contracts.Person;
Что будем делать, когда персон будет 200?
Я предлагаю сделать всё-таки выбор персон через селектбокс с мультивыбором. А ещё лучше - привязывать топики через мультиселектбокс на этапе создания\редактирования персоны.

2021-04-19 13:21 UTC, itbeard commented on Pds/Pds.Api/Properties/launchSettings.json
> -  "$schema": "http://json.schemastore.org/launchsettings.json",
Изменения в этом файле лишние, их не должно быть в ПР

2021-04-19 13:21 UTC, itbeard commented on Pds/Pds.Api/appsettings.json
> -    "DefaultConnection": "Server=localhost;Initial Catalog=pds;User ID=admin;Password=123qweQWE;MultipleActiveResultSets=False;"
Изменения в этом файле лишние, их не должно быть в ПР

2021-04-19 13:26 UTC, itbeard commented on Pds/Pds.Data/Entities/Person.cs
> +        public virtual ICollection<PersonTopic> PersonTopics { get; set; }
Связь многое-ко-многому создается автоматически (с какой-то версии EF), тебе не надо ее руками прописывать. 
Удаляй код, связанный с PersonTopics и посмотри как это реализовано на примере Brands и Persons (там тоже many-to-many).
На будущее - таблицы с такими связями менуются обычно либо во множественном либо в единственном числе для обоих составляющих (BrandPerson or BrandsPersons). EF делает это по-умолчанию в единственном.

2021-04-19 13:26 UTC, itbeard commented on Pds/Pds.Data/ApplicationDbContext.cs
> +            modelBuilder.Entity<PersonTopic>()
Связь многое-ко-многому создается автоматически (с какой-то версии EF), тебе не надо ее руками прописывать.

2021-04-19 13:26 UTC, itbeard commented on Pds/Pds.Data/ApplicationDbContext.cs
> +            modelBuilder.Entity<PersonTopic>()
Связь многое-ко-многому создается автоматически (с какой-то версии EF), тебе не надо ее руками прописывать.

2021-04-19 13:26 UTC, itbeard commented on Pds/Pds.Data/ApplicationDbContext.cs
> +            modelBuilder.Entity<PersonTopic>()
Связь многое-ко-многому создается автоматически (с какой-то версии EF), тебе не надо ее руками прописывать.

2021-04-19 13:26 UTC, itbeard commented on Pds/Pds.Data/ApplicationDbContext.cs
> +        public DbSet<PersonTopic> PersonTopics { get; set; }
Связь многое-ко-многому создается автоматически (с какой-то версии EF), тебе не надо ее руками прописывать.

2021-04-19 13:28 UTC, itbeard commented on Pds/Pds.Data/Entities/PersonTopic.cs
> +    public class PersonTopic : IEquatable<PersonTopic>
Этот класс не нужен, описал выше почему

2021-04-19 13:28 UTC, itbeard commented on Pds/Pds.Data/Entities/Topic.cs
> +        public Topic()
констуркторы в сущностях БД не нужны

2021-04-19 13:29 UTC, itbeard commented on Pds/Pds.Data/Entities/Topic.cs
> +        public virtual ICollection<PersonTopic> PersonTopics { get; set; }
лишнее

2021-04-19 13:29 UTC, itbeard commented on Pds/Pds.Data/Entities/Topic.cs
> +        public virtual ICollection<PersonTopic> PersonTopics { get; set; }
вместо этого добавь коллекцию персон

2021-04-19 13:29 UTC, itbeard commented on Pds/Pds.Data/IUnitOfWork.cs
> +        IPersonTopicRepository PersonTopics { get; }
лишнее

2021-04-19 13:30 UTC, itbeard commented on Pds/Pds.Data/Repositories/Interfaces/ITopicRepository.cs
> +    public interface ITopicRepository : IRepositoryBase<Topic>
лишний класс

2021-04-19 13:30 UTC, itbeard commented on Pds/Pds.Data/Repositories/PersonTopicRepository.cs
> +    public class PersonTopicRepository : RepositoryBase<PersonTopic>, IPersonTopicRepository
лишний класс

2021-04-19 13:32 UTC, itbeard commented on Pds/Pds.Web/wwwroot/index.html
> +    <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/js/bootstrap.min.js" integrity="sha384-oesi62hOLfzrys4LxRF63OJCXdXDipiYWBnvTl9Y9/TRlw5xlKIEHpNyvvDShgf/" crossorigin="anonym
никакого левого джээса. удаляй эти две либы. попапы делаем на си шарпе

2021-04-19 14:23 UTC, Alex2021cyberhuman commented on Pds/Pds.Api.Contracts/Topic/CheckBoxPersonDto.cs
> +﻿using Pds.Api.Contracts.Person;
Это уже фича #32 я так понимаю.

2021-04-20 13:57 UTC, itbeard commented on Pds/Pds.sln
>  		{70D0A540-869E-48C3-8693-81A466F52070} = {B452C78D-1671-442B-AC8E-7EFEA7483F58}
Это что за проеткы новые подьехали?

2021-04-20 13:58 UTC, itbeard requested changes
не все пофикшено из предыдущей проверки. Смотри что там за изменения в файлах проектов

2021-04-23 12:39 UTC, closed without merging