Ayasinovsky/feature/30
it-beard/bloggers-cms pull request #131
Opened 2021-04-23 12:50 UTC by Alex2021cyberhuman

#30

2021-04-30 19:58 UTC, itbeard requested changes

2021-04-30 19:58 UTC, itbeard commented on Pds/Pds.Api/Properties/launchSettings.json
> -﻿{
Убери плз все изменения из этого файла, они не нужны

2021-04-30 19:58 UTC, itbeard commented on Pds/Pds.Data/ApplicationDbContext.cs
> +
лишняя строка

2021-04-30 19:58 UTC, itbeard commented on Pds/Pds.Data/ApplicationDbContext.cs
> +
лишняя строка

2021-04-30 19:58 UTC, itbeard commented on Pds/Pds.Data/Entities/Person.cs
> +        [Column(TypeName = "varchar(300)")] public string ThirdName { get; set; }
это должно быт ьв две строки как раньше

2021-04-30 19:58 UTC, itbeard commented on Pds/Pds.Data/Entities/Topic.cs
> +        public void Archive()
В энтитях не должно быть логики

2021-04-30 19:58 UTC, itbeard commented on Pds/Pds.Data/Entities/Topic.cs
> +        public void Unarchive()
В энтитях не должно быть логики. Лишний метод.

2021-04-30 19:58 UTC, itbeard commented on Pds/Pds.Data/Repositories/TopicRepository.cs
> +        public async Task<Topic> GetFirstWithPeople(Expression<Func<Topic, bool>> match)
Забыл постфикс Async в названии метода

2021-04-30 19:58 UTC, itbeard commented on Pds/Pds.Mappers/ApiMappingProfile.cs
> +                        .MapFrom((p, s) =>
Это автозамена? Если да, то не нужно

2021-04-30 19:58 UTC, itbeard commented on Pds/Pds.Mappers/ApiMappingProfile.cs
> +                            s.Title = string.IsNullOrEmpty(p.Title)
Это автозамена? Если да, то не нужно

2021-04-30 19:58 UTC, itbeard commented on Pds/Pds.Mappers/ApiMappingProfile.cs
> +using ClientForLookupDto = Pds.Api.Contracts.Content.ClientForLookupDto;
В файле маппинга очень много ссылок,  в которых легко запутаться. Поэтому алиасы тут только путают, лучше писат ьполный путь в классу там, где ты его применяешь.

2021-04-30 19:58 UTC, itbeard commented on Pds/Pds.Services/Interfaces/ITopicService.cs
> +        Task<Topic> FindById(Guid id);
Постфикс Async

2021-04-30 19:58 UTC, itbeard commented on Pds/Pds.Services/Services/ClientService.cs
> +            if (client == null) throw new ArgumentNullException(nameof(client));
Фигурные ковычки используем всегда (обсуждали на синкапколе, внесу в стайлгайды)

2021-04-30 19:58 UTC, itbeard commented on Pds/Pds.Services/Services/ClientService.cs
> -            {
Фигурные ковычки используем всегда (обсуждали на синкапколе, внесу в стайлгайды)

2021-04-30 19:58 UTC, itbeard commented on Pds/Pds.Services/Services/ClientService.cs
> -            {
Фигурные ковычки используем всегда (обсуждали на синкапколе, внесу в стайлгайды)

2021-04-30 19:58 UTC, itbeard commented on Pds/Pds.Services/Services/ClientService.cs
> +            if (model == null) throw new ClientEditException("Модель запроса пуста.");
Фигурные ковычки используем всегда (обсуждали на синкапколе, внесу в стайлгайды)

2021-04-30 19:58 UTC, itbeard commented on Pds/Pds.Services/Services/ClientService.cs
> +            if (client == null) throw new ClientEditException($"Клиент с id {model.Id} не найден.");
Фигурные ковычки используем всегда (обсуждали на синкапколе, внесу в стайлгайды)

2021-04-30 19:58 UTC, itbeard commented on Pds/Pds.Services/Services/ClientService.cs
> -            {
Фигурные ковычки используем всегда (обсуждали на синкапколе, внесу в стайлгайды)

2021-04-30 19:58 UTC, itbeard commented on Pds/Pds.Services/Services/ClientService.cs
> -            {
Фигурные ковычки используем всегда (обсуждали на синкапколе, внесу в стайлгайды)

2021-04-30 19:58 UTC, itbeard commented on Pds/Pds.Services/Services/TopicService.cs
> +        public Task<Topic> FindById(Guid id)
Постфикс Async

2021-04-30 19:58 UTC, itbeard commented on Pds/Pds.Web/Common/CustomJSRuntimeCaller.cs
> +        public async Task InvokeHistoryBack()
У нас есть свой HistoryBack, смотри BaseComponent

2021-04-30 19:58 UTC, itbeard commented on Pds/Pds.Web/Common/CustomJSRuntimeCaller.cs
> +        public async Task InvokeHistoryBack()
дотнетный

2021-04-30 19:58 UTC, itbeard commented on Pds/Pds.Web/Common/CustomJSRuntimeCaller.cs
> +        public async Task<bool> InvokeConfirm(string question)
Это лучше вынести в BaseComponent

2021-04-30 19:58 UTC, itbeard commented on Pds/Pds.Web/Pages/Topics/Create.razor
> +@attribute [Authorize]
Лишнее, авторизация висит на BasePageComponent

2021-04-30 19:58 UTC, itbeard commented on Pds/Pds.Web/Common/CustomJSRuntimeCaller.cs
> +        public async Task InvokeHistoryBack()
BasePageComponent

2021-04-30 19:58 UTC, itbeard commented on Pds/Pds.Web/Common/CustomJSRuntimeCaller.cs
> +        public async Task<bool> InvokeConfirm(string question)
BasePageComponent

2021-04-30 19:58 UTC, itbeard commented on Pds/Pds.Web/Pages/Topics/Edit/Body.razor
> +@attribute [Authorize]
Лишнее. Авторизация висит на родительском BasePageComponent

2021-04-30 19:58 UTC, itbeard commented on Pds/Pds.Web/Pages/Topics/Edit/Body.razor
> +    private async Task<GetTopicResponse> GetTopicResponse()
постфикс упущен

2021-04-30 19:58 UTC, itbeard commented on Pds/Pds.Web/Pages/Topics/Edit/Body.razor
> +    private async Task HandleSubmit()
постфикс упущен

2021-04-30 19:58 UTC, itbeard commented on Pds/Pds.Web/Pages/Topics/Edit/Body.razor
> +    private async Task RefreshPeopleCheckBox()
постфикс упущен

2021-04-30 19:58 UTC, itbeard commented on Pds/Pds.Web/Pages/Topics/Info/Body.razor
> +@attribute [Authorize]
лишнее, дублирует BasePageComponent

2021-04-30 19:58 UTC, itbeard commented on Pds/Pds.Web/Pages/Topics/Info/InfoActions.razor
> +    private async Task OnArchive()
постфикс упущен

2021-04-30 19:58 UTC, itbeard commented on Pds/Pds.Web/Pages/Topics/Info/InfoActions.razor
> +        var confirmed = await JsRuntime.InvokeAsync<bool>("confirm", $"Уверены, что хотите архивировать тему {CurrentTopic.Name}?");
Используй InvokeConfirm из BasePAgeCompmponent

2021-04-30 19:58 UTC, itbeard commented on Pds/Pds.Web/Pages/Topics/Info/InfoActions.razor
> +    private async Task OnUnarchive()
постфикс упущен

2021-04-30 19:58 UTC, itbeard commented on Pds/Pds.Web/Pages/Topics/List/Actions.razor
> +    private async Task OnArchive()
постфикс упущен

2021-04-30 19:58 UTC, itbeard commented on Pds/Pds.Web/Pages/Topics/List/Actions.razor
> +        var confirmed = await JsRuntime.InvokeAsync<bool>("confirm", $"Уверены, что хотите архивировать тему {CurrentTopic.Name}?");
используй InvokeComfirm из базового компонента

2021-04-30 19:58 UTC, itbeard commented on Pds/Pds.Web/Pages/Topics/List/Actions.razor
> +        var confirmed = await JsRuntime.InvokeAsync<bool>("confirm", $"Уверены, что хотите разархивировать тему {CurrentTopic.Name}?");
используй InvokeComfirm из базового компонента

2021-04-30 19:58 UTC, itbeard commented on Pds/Pds.Web/Pages/Topics/List/Actions.razor
> +    private async Task OnUnarchive()
постфикс упущен

2021-04-30 19:58 UTC, itbeard commented on Pds/Pds.Web/Pages/Topics/List/Body.razor
> +@attribute [Authorize]
Унаследуйся от BasePageComponent - атворизация на его уровне висит

2021-04-30 19:58 UTC, itbeard commented on Pds/Pds.Web/Pages/Topics/List/Body.razor
> +    private async Task<GetTopicCollectionResponse> GetTopicsInfo()
постфикс упущен

2021-04-30 19:58 UTC, itbeard commented on Pds/Pds.sln
> +EndGlobal
это лишнее

2021-05-07 03:20 UTC, Alex2021cyberhuman commented on Pds/Pds.Api/Properties/launchSettings.json
> -﻿{
https://github.com/it-beard/bloggers-cms/commit/19219152e8a5eb4670918fe5c4505713b84d23fd

2021-05-07 03:22 UTC, Alex2021cyberhuman commented on Pds/Pds.Data/ApplicationDbContext.cs
> +
https://github.com/it-beard/bloggers-cms/commit/837569b635aa00d60e55fa0f7e1a9b00703ea0b3#r50497824

2021-05-07 03:24 UTC, Alex2021cyberhuman commented on Pds/Pds.Data/ApplicationDbContext.cs
> +
Там так и было

2021-05-07 03:27 UTC, Alex2021cyberhuman commented on Pds/Pds.Data/Entities/Person.cs
> +        [Column(TypeName = "varchar(300)")] public string ThirdName { get; set; }
https://github.com/it-beard/bloggers-cms/commit/7928023d9a081873fa5c732518fc5b16b972298f

2021-05-07 03:27 UTC, Alex2021cyberhuman commented on Pds/Pds.Data/Entities/Topic.cs
> +        public void Archive()
https://github.com/it-beard/bloggers-cms/commit/c63a41d6fd333eec89e4a8b0f09d9de1c0b95947

2021-05-07 06:38 UTC, Alex2021cyberhuman commented on Pds/Pds.Web/Pages/Topics/List/Actions.razor
> +        var confirmed = await JsRuntime.InvokeAsync<bool>("confirm", $"Уверены, что хотите разархивировать тему {CurrentTopic.Name}?");
Не хочу навязывать свою реализацию InvokeConfirm.  В других компонентах так же как и здесь https://github.com/it-beard/bloggers-cms/blob/bc5ce2b3767ef07e77334bf72bf90095d88641ea/Pds/Pds.Web/Pages/Clients/List/Actions.razor#L37

2021-05-07 07:32 UTC, Alex2021cyberhuman commented on Pds/Pds.Web/Pages/Topics/List/Body.razor
> +    private async Task<GetTopicCollectionResponse> GetTopicsInfo()
исправил постфиксы в моей части

2021-05-07 09:16 UTC, Alex2021cyberhuman commented on Pds/Pds.Mappers/ApiMappingProfile.cs
> +                        .MapFrom((p, s) =>
![Разница с develop](https://user-images.githubusercontent.com/59359082/117427690-bab21c00-af3e-11eb-9d55-08b76c228267.png)

2021-05-07 09:17 UTC, Alex2021cyberhuman commented on Pds/Pds.Mappers/ApiMappingProfile.cs
> +                        .MapFrom((p, s) =>
слева develop

2021-05-07 09:17 UTC, Alex2021cyberhuman commented on Pds/Pds.Services/Services/ClientService.cs
> +            if (client == null) throw new ArgumentNullException(nameof(client));
Я случайно изменил этот файл и забыл про это

2021-05-07 09:17 UTC, Alex2021cyberhuman commented on Pds/Pds.Services/Services/ClientService.cs
> +            if (client == null) throw new ArgumentNullException(nameof(client));
Уже исправил

2021-05-07 09:23 UTC, Alex2021cyberhuman commented on Pds/Pds.Web/Common/CustomJSRuntimeCaller.cs
> +        public async Task InvokeHistoryBack()
удалил

2021-05-07 09:24 UTC, Alex2021cyberhuman commented on Pds/Pds.Web/Common/CustomJSRuntimeCaller.cs
> +        public async Task<bool> InvokeConfirm(string question)
Я уже его удалил

2021-05-07 09:25 UTC, Alex2021cyberhuman commented on Pds/Pds.Web/Pages/Topics/Create.razor
> +@attribute [Authorize]
исправил

2021-05-07 09:27 UTC, Alex2021cyberhuman commented
Теперь, я думаю, можно мержить.

2021-05-12 13:15 UTC, merged