Add to the list of persons filtering by brands
it-beard/bloggers-cms pull request #133
Opened 2021-04-28 06:25 UTC by catdog50rus

#9
Filtering by brands has been added to the list of persons

2021-04-30 20:03 UTC, itbeard requested changes

2021-04-30 20:03 UTC, itbeard commented on Pds/Pds.Api.Contracts/Paging/PageSettings.cs
> +    public class SearchSettings
Если это фильтеринг, зачем менять название класса?

2021-04-30 20:03 UTC, itbeard commented on Pds/Pds.Api.Contracts/Paging/PageSettings.cs
> +        public SearchSettings FilterSettings { get; set; }
тут название класса поменял, а проперти осталось. Наверно лучше прост оне менять класс)

2021-04-30 20:03 UTC, itbeard commented on Pds/Pds.Web/Pages/Persons/List/Body.razor
> +        searchSettings = new SearchSettings
непонятно изменение названия

2021-04-30 20:03 UTC, itbeard commented on Pds/Pds.Api.Contracts/Paging/PageSettings.cs
> +        public SearchSettings FilterSettings { get; set; }
или же уже менять везде

2021-05-05 10:38 UTC, catdog50rus commented on Pds/Pds.Api.Contracts/Paging/PageSettings.cs
> +    public class SearchSettings
Наименование класса изначально было выбрано неверно. Так как предполагалось поиск и фильтрацию проводить на сервере. В класс должно было добавиться свойство отвечающее за фильтрацию и на основе это класса строиться предикат. Сейчас это только поиск, поэтому имеет смысл переименовать класс в соответствии с функционалом

2021-05-05 10:38 UTC, catdog50rus commented on Pds/Pds.Api.Contracts/Paging/PageSettings.cs
> +        public SearchSettings FilterSettings { get; set; }
Этот абстрактный класс создавался видимо для передачи настроек страницы запросом на сервер. Сейчас этот класс не используется совсем. Единственная ссылка в Develop на этот класс была из моего body.razor и я это изменяю в этом ПР. Предлагаю исключить  класс совсем!

2021-05-05 10:38 UTC, catdog50rus commented on Pds/Pds.Web/Pages/Persons/List/Body.razor
> +        searchSettings = new SearchSettings
Название меняется в соответствии с новым названием класса из файла Pds/Pds.Api.Contracts/Paging/PageSettings.cs

2021-05-06 11:00 UTC, itbeard approved these changes

2021-05-06 11:03 UTC, merged